name: Check Homework

on:
  pull_request:
    branches:
      - main

jobs:
  check_code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Run homework checker
        id: run-homework-checker
        run: |
          python scripts/homework_checker.py > result.log

      - name: Add feedback as a comment on PR
        uses: actions/github-script@v6
        if: ${{ github.event_name == 'pull_request' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} #  <--- Здесь ключ
        with:
          script: |
            const fs = require('fs');
            const resultLog = fs.readFileSync('${{ github.workspace }}/result.log', 'utf8');
            const commentBody = `
            ### Feedback for Homework:

            \`\`\`
            ${resultLog}
            \`\`\`
            `;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            });

