name: Check Homework

on:
  pull_request:
    branches:
      - main  # Или другая ветка, куда студенты делают PR

jobs:
  check_code:
    runs-on: ubuntu-latest  # Используем виртуальную машину Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Check for similar open PRs
        id: check-similar-prs
        run: |
          # Получаем список всех открытых PR
          OPEN_PRS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls?state=open")
          
          # Заголовок текущего PR
          CURRENT_PR_TITLE="${{ github.event.pull_request.title }}"

          #
